name = "mimir/misignal"
version = "0.1.2"
authors = ["mimir"]
license = "MIT"

includes = ["pesde.toml", "README.md", "LICENSE", "src/**/*"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"